### ISSUE TITLE
add table header to fax pdf

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#32] opened 2013-05-17 10:15 UTC
at the moment we can export a order for one supplier to pdf so the supplier knows what to send to the foodcoop. on the top of the table with names, amounts and prices there are at the moment no titles which is confusing for the suppliers. 

solution:
add titles to the columns in order pdf to identify what each column means.

![screen shot 2013-05-17 at 12 11 55 pm](https://f.cloud.github.com/assets/3144698/517380/a93d15da-bedb-11e2-802d-fc9efd9fd8b3.png)

**Comment by wvengen** [comment] 2013-05-17 18:23
Duplicate of foodcoops/foodsoft#109 planned upstream for foodsoft 4.1. We can apply the fix suggested there.

**Closed as completed** 2013-06-20 23:07 UTC
Labels: easy to fix
